apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "cloudwatch-fetcher.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ include "cloudwatch-fetcher.fullname" . }}
data:
  logging_config.ini: {{ toYaml .Values.loggingConfig | indent 2 }}
  config.yaml: {{ toYaml .Values.fetcherConfig | indent 2 }}