{{- if .Values.persistentVolume.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cloudwatch-fetcher.fullname" . }}
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  accessModes:
    {{- range .Values.persistentVolume.accessModes }}
      - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.resources.requests.storage }}
{{- end }}