{{ if .Values.enabled }}
{{- if .Values.secret.enabled -}}
apiVersion: {{ .Values.apiVersions.secret }}
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  logzio-log-shipping-token: {{ required "Logzio shipping token is required!" (.Values.logzioLogsToken | default .Values.global.logzioLogsToken) }}
  logzio-log-listener: {{ template "logzio.listenerHost" . }}
{{- end }}
{{ end }}
