apiVersion: v1
appVersion: "0.10.0"
description: A fork of prometheus-cloudwatch-exporter helm chart by logz.io
name: logzio-cloudwatch-exporter
version: 0.14.1
home: https://github.com/prometheus/cloudwatch_exporter
sources:
- https://github.com/prometheus/cloudwatch_exporter
keywords:
- aws
- cloudwatch
- prometheus
- exporter

# credit to original chart maintainers : gianrubio@gmail.com, mail@torstenwalter.de, asher@asherfoa.com
maintainers:
- name: yotamloe
  email: yotam.loewenbach@logz.io

dependencies:
  - name: logzio-otel-k8s-metrics
    version: "0.1.0"
    repository: https://logzio.github.io/logzio-helm
    condition: openTelemtryCollector.enabled