{{ $operatorEnabled := index .Values "otel-operator" "enabled" }}
{{- if $operatorEnabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "otel-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "otel-operator.annotations" . | nindent 4 }}
    {{- include "otel-operator.cleanupAnnotations" . | nindent 4 }}
    helm.sh/hook-weight: "1"
  labels:
    {{- include "otel-operator.labels" . | nindent 4 }}
{{- end -}}