{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "trivy-to-logzio.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
    - "aquasecurity.github.io"
    - ""
    - apps
    resources:
    - namespaces
    - vulnerabilityreports
    - pods
    - replicasets
    - deployments
    verbs:
    - get
    - list
    - watch
{{- end -}}