apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "trivy-to-logzio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ include "trivy-to-logzio.fullname" . }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            k8s-app: {{ include "trivy-to-logzio.fullname" . }}
        spec:
          serviceAccount: {{ template "trivy-to-logzio.serviceAccount" . }}
          serviceAccountName: {{ template "trivy-to-logzio.serviceAccount" . }}
          restartPolicy: {{ .Values.restartPolicy }}
          containers:
          - name: trivy-to-logzio
            image: "{{ .Values.image }}:{{ .Values.imageTag }}"
            imagePullPolicy: Always
            env:
            - name: LOGZIO_LOG_SHIPPING_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: logzio-log-shipping-token
            - name: LOGZIO_LOG_LISTENER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: logzio-log-listener
            - name: ENV_ID
              value: {{ .Values.env_id }}
          terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}