{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.namespace }}
type: Opaque
stringData:
  logzio-log-shipping-token: {{ required "Logzio shipping token is required!" .Values.secrets.logzioShippingToken }}
  logzio-log-listener: {{ template "trivyToLogzio.listenerHost" . }}
{{- end }}
