{{- if .Values.managedServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: metricbeat
  labels:
    k8s-app: metricbeat
rules: {{ toYaml .Values.clusterRoleRules | nindent 2 -}}
{{- end -}}