{{- if .Values.managedServiceAccount }}
apiVersion: {{ .Values.apiVersions.ClusterRoleBinding }}
kind: ClusterRoleBinding
metadata:
  name: metricbeat
subjects:
- kind: ServiceAccount
  name: {{ template "metricbeat.serviceAccount" . }}
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: metricbeat
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
