{{- if .Values.logzioCert }}
---
apiVersion: {{ .Values.apiVersions.ConfigMap }}
kind: ConfigMap
metadata:
  name: logzio-cert
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: metricbeat
data:
{{- range $path, $config := .Values.logzioCert }}
  {{ $path }}: |-
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}

{{- if .Values.metricbeatConfig }}
---
apiVersion: {{ .Values.apiVersions.ConfigMap }}
kind: ConfigMap
metadata:
  name: metricbeat-config
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: metricbeat
data:
{{- if eq .Values.configType "standard" }}
{{- range $path, $config := .Values.metricbeatConfig.standardConfig }}
  {{ $path }}: |-
{{ $config | indent 4 -}}
{{- end -}}
{{- else if eq .Values.configType "autodiscover" }}
{{- range $path, $config := .Values.metricbeatConfig.autodiscoverConfig }}
  {{ $path }}: |-
{{ $config | indent 4 -}}
{{- end -}}
{{- else if eq .Values.configType "auto-custom" }}
{{- range $path, $config := fromYaml .Values.metricbeatConfig.autoCustomConfig }}
  {{ $path }}: |-
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{- if .Values.daemonset.metricbeatConfig }}
---
apiVersion: {{ .Values.apiVersions.ConfigMap }}
kind: ConfigMap
metadata:
  name: metricbeat-daemonset-modules
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: metricbeat
data:
{{- include "metricbeat.chosenDaemonsetConfig" . }}
{{- end -}}

{{- if .Values.deployment.metricbeatConfig }}
---
apiVersion: {{ .Values.apiVersions.ConfigMap }}
kind: ConfigMap
metadata:
  name: metricbeat-deployment-modules
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: metricbeat
data:
{{- include "metricbeat.chosenDeploymentConfig" . }}
{{- end -}}
