apiVersion: {{ .Values.apiVersions.Secrets }}
kind: Secret
metadata:
  name: logzio-metrics-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  logzio-metrics-shipping-token: {{ .Values.secrets.MetricsToken }}
  logzio-metrics-listener-host: {{ .Values.secrets.ListenerHost }}
---
apiVersion: {{ .Values.apiVersions.Secrets }}
kind: Secret
metadata:
  name: cluster-details
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  kube-state-metrics-namespace: {{ .Values.secrets.KubeStatNamespace }}
  kube-state-metrics-port: {{ .Values.secrets.KubeStatPort | quote }}
  cluster-name: {{ .Values.secrets.ClusterName }}
