{{- if .Values.managedServiceAccount }}
apiVersion: {{ .Values.apiVersions.ServiceAccount }}
kind: ServiceAccount
metadata:
  name: metricbeat
  namespace: kube-system
  labels:
    k8s-app: metricbeat
{{- end -}}
