apiVersion: {{ .Values.apiVersions.secret }}
kind: Secret
metadata:
  name: logzio-logs-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  logzio-logs-shipping-token: {{ .Values.secrets.logzioShippingToken }}
  logzio-logs-listener: {{ .Values.secrets.logzioListener }}
  cluster-name: {{ .Values.secrets.clusterName }}