{{- if eq .Values.Configs.AgentBrand "otel"}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-config
  namespace: {{ .Values.Configs.Namespace}}
  labels:
    app: otel-logzio
    component: agent-confing
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
      opencensus:
      jaeger:
        protocols:
          grpc:
          thrift_http:
      zipkin:

    exporters:
      otlp:
        endpoint: "{{ .Values.Configs.CollectorBrand }}-collector-logzio:14250"
        insecure: true
      logging:
        loglevel: debug

    processors:
      batch:

    extensions:
      pprof:
        endpoint: :1777
      zpages:
        endpoint: :55679
      health_check:

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp, opencensus, jaeger, zipkin]
          processors: [batch]
          exporters: [otlp, logging]
{{- end -}}