{{ if and (.Values.enabled) (.Values.spm.enabled) }}
{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spm-collector.fullname" . }}
  namespace: {{ template "apm-collector.namespace" . }}
  labels: {{- include "apm-collector.labels" . | nindent 4 }}
data:
  relay: {{ include "spm-collector.config" . | nindent 4 }}
{{- end }}
{{ end }}
