{{ if and .Values.enabled (or .Values.spm.enabled .Values.serviceGraph.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spm-collector.fullname" . }}
  namespace: {{ template "apm-collector.namespace" . }}
  labels:
    {{- include "apm-collector.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.standaloneCollector.replicaCount }}
  selector:
    matchLabels:
      {{- include "apm-collector.selectorLabels" . | nindent 6 }}
      {{- include "spm-collector.component" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-spm.yaml") . | sha256sum }}
        {{- include "apm-collector.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "apm-collector.selectorLabels" . | nindent 8 }}
        {{- include "apm-collector.podLabels" . | nindent 8 }}
        {{- include "spm-collector.component" . | nindent 8 }}
    spec:
      {{- include "spm-collector.pod" . | nindent 6 }}
      hostNetwork: {{ .Values.hostNetwork }}
      {{- with .Values.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
