{{ $operatorEnabled := index .Values "otel-operator" "enabled" }}
{{ if and .Values.enabled $operatorEnabled }}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ include "apm-collector.fullname" . }}
  namespace: {{ .Values.instrumentation.includeNamespaces | default (include "apm-collector.namespace" .) }}
  labels:
    {{- include "apm-collector.labels" . | nindent 4 }}
    {{- include "apm-collector.component" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  exporter:
    endpoint: {{ include "apm-collector.serviceAddr" . }}:4317
  propagators:
    {{- $defaultPropagators := list "tracecontext" "baggage" }}
    {{- range .Values.instrumentation.propagators | default $defaultPropagators }}
    - {{ . }}
    {{- end }}
  {{- with .Values.instrumentation.sampler }}
  sampler:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  # Python, .NET, Go and Java autoinstrumentation uses http/proto by default
  # so data must be sent to 4318 instead of 4317.
  python:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: {{ include "apm-collector.serviceAddr" . }}:4318
  dotnet:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: {{ include "apm-collector.serviceAddr" . }}:4318
  go:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: {{ include "apm-collector.serviceAddr" . }}:4318
  java:
    env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ include "apm-collector.serviceAddr" . }}:4318
{{ end }}
