{{ if .Values.enabled}}
{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  env-id: {{ .Values.global.env_id | default .Values.secrets.env_id | quote }}
  logzio-listener-region: {{ .Values.global.logzioRegion | default .Values.secrets.logzioRegion }}
  {{- template "check-tracing-token" . }}
  logzio-traces-token: {{ .Values.global.logzioTracesToken | default .Values.secrets.logzioTracesToken }}
  {{- end }}
  {{- template "check-spm-token" . }}
  logzio-spm-token: {{ .Values.global.logzioSpmToken | default .Values.secrets.logzioSpmToken }}
  {{- end }}
  {{- if .Values.secrets.customEndpoint}}
  custom-traces-endpoint: {{ .Values.secrets.customTracesEndpoint }}
  {{- end }}
  {{- if .Values.secrets.customEndpoint}}
  custom-spm-endpoint: {{ .Values.secrets.customSpmEndpoint }}
  {{- end }}
{{- end }}
{{ end }}
