{{ if .Values.enabled}}
{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  env-id: {{ include "getGlobalOrDefaultValue" (list . "env_id" .Values.secrets.env_id) | quote }}
  logzio-listener-region: {{ include "getGlobalOrDefaultValue" (list . "logzioRegion" .Values.secrets.logzioRegion) }}
  {{- template "check-tracing-token" . }}
  logzio-traces-token: {{ include "getGlobalOrDefaultValue" (list . "logzioTracesToken" .Values.secrets.logzioTracesToken) }}
  {{- template "check-spm-token" . }}
  logzio-spm-token: {{ include "getGlobalOrDefaultValue" (list . "logzioSpmToken" .Values.secrets.logzioSpmToken) }}
  {{- if .Values.secrets.customTracesEndpoint }}
  custom-traces-endpoint: {{ .Values.secrets.customTracesEndpoint }}
  {{- end }}
  {{- if .Values.secrets.customSpmEndpoint}}
  custom-spm-endpoint: {{ .Values.secrets.customSpmEndpoint }}
  {{- end }}
{{- end }}
{{ end }}
