{{ if .Values.enabled}}
{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  env-id: {{ template "getValueOrDefault" "env_id" | quote }}
  logzio-listener-region: {{ template "getValueOrDefault" "logzioRegion" }}
  {{- template "check-tracing-token" . }}
  logzio-traces-token: {{ template "getValueOrDefault" "logzioTracesToken" }}
  {{- template "check-spm-token" . }}
  logzio-spm-token: {{ template "getValueOrDefault" "logzioSpmToken" }}
  {{- if .Values.secrets.customTracesEndpoint}}
  custom-traces-endpoint: {{ .Values.secrets.customTracesEndpoint }}
  {{- end }}
  {{- if .Values.secrets.customSpmEndpoint}}
  custom-spm-endpoint: {{ .Values.secrets.customSpmEndpoint }}
  {{- end }}
{{- end }}
{{ end }}
