{{ if .Values.enabled}}
{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  env-id: {{ .Values.global.env_id | quote}}
  logzio-listener-region: {{ .Values.global.logzioRegion | quote}}
  {{- template "check-tracing-token" . }}
  logzio-traces-token: {{ .Values.global.logzioTracesToken }}
  {{- template "check-spm-token" . }}
  logzio-spm-token: {{ .Values.global.logzioSpmToken }}
  {{- if .Values.global.customTracesEndpoint }}
  custom-traces-endpoint: {{ .Values.global.customTracesEndpoint }}
  {{- end }}
  {{- if .Values.global.customSpmEndpoint}}
  custom-spm-endpoint: {{ .Values.global.customSpmEndpoint }}
  {{- end }}
{{- end }}
{{ end }}
