{{ if .Values.enabled}}
{{- if (.Values.serviceAccount.create) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "apm-collector.serviceAccountName" . }}
  namespace: {{ template "apm-collector.namespace" . }}
  labels:
    {{- include "apm-collector.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := .Values.serviceAccount.annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
{{ end }}
{{ end }}
