{{- if and (eq .Values.collector.mode "daemonset") (.Values.metrics.enabled) }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "opentelemetry-collector.daemonsetFullname" . }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "opentelemetry-collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.daemonsetCollector.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "opentelemetry-collector.selectorLabels" . | nindent 8 }}
        {{- with .Values.daemonsetCollector.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- $podValues := deepCopy .Values.daemonsetCollector | mustMergeOverwrite (deepCopy .Values) }}
      {{- $podData := dict "Values" $podValues "configmapSuffix" "" "isAgent" false }}
      {{- include "opentelemetry-collector.daemonset-pod" ($podData | mustMergeOverwrite (deepCopy .)) | nindent 6 }}
{{- end }}