{{- if or .Values.traces.enabled .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opentelemetry-collector.serviceName" . }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  # Check ports of otel-traces
  ports:
    {{- range $key, $port := .Values.ports }}
    {{- $shouldEnable := $port.enabled }}
    {{- if eq $key "signalfx" }}
      {{- $shouldEnable = and $.Values.metrics.enabled $.Values.signalFx.enabled }}
    {{- end }}
    {{- if eq $key "carbon" }}
      {{- $shouldEnable = and $.Values.metrics.enabled $.Values.carbon.enabled }}
    {{- end }}
    {{- if $shouldEnable }}
    - name: {{ $key }}
      port: {{ $port.servicePort }}
      targetPort: {{ $key }}
      protocol: {{ $port.protocol }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "opentelemetry-collector.selectorLabels" . | nindent 4 }}
{{- end }}
