{{- if eq .Values.Configs.AgentBrand "otel"}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-config
  namespace: {{ .Release.Namespace}}
  labels:
    app: otel-logzio
    component: agent-confing
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
      opencensus:
      jaeger:
        protocols:
          grpc:
          thrift_http:
          thrift_compact:
      zipkin:

    exporters:
      logzio:
          account_token: ${LOGZIO_TRACES_TOKEN}
          region: {{ .Values.Configs.Region }}

      logging:
        loglevel: info

    processors:
      memory_limiter:
        ballast_size_mib: 2000
        check_interval: 1s
        limit_mib: 4000
        spike_limit_mib: 800
      batch:
        send_batch_size: 10000
        timeout: 5s
      probabilistic_sampler:
        hash_seed: 22
        sampling_percentage: 1
      k8s_tagger:
        passthrough: true

    extensions:
      pprof:
        endpoint: :1777
      zpages:
        endpoint: :55679
      health_check:

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp, opencensus, jaeger, zipkin]
          processors: [batch, memory_limiter, probabilistic_sampler, k8s_tagger]
          exporters:
            - logging
            - logzio
{{- end -}}