{{- if eq .Values.Configs.AgentBrand "otel"}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-config
  namespace: {{ .Release.Namespace}}
  labels:
    app: otel-logzio
    component: agent-confing
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
      opencensus:
      jaeger:
        protocols:
          grpc:
          thrift_http:
          thrift_compact:
      zipkin:

    exporters:
      logzio:
          account_token: ${LOGZIO_TRACES_TOKEN}
          region: {{ .Values.Configs.Region }}

      logging:
        loglevel: info

    processors:
      batch:

    extensions:
      pprof:
        endpoint: :1777
      zpages:
        endpoint: :55679
      health_check:

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp, opencensus, jaeger, zipkin]
          processors: [batch]
          exporters:
            - logging
            - logzio
{{- end -}}