{{- if and (eq .Values.Configs.CollectorBrand "otel") (ne .Values.Configs.AgentBrand "otel") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: otel-logzio
    component: otel-collector-conf
data:
  config.yaml: |
    receivers:
      opencensus:
      zipkin:
        endpoint: :9411
      jaeger:
        protocols:
          thrift_http:
          grpc:

    exporters:
      logzio:
        account_token: "${LOGZIO_TRACES_TOKEN}"
        region: {{ .Values.Configs.Region }}    # Replace with the 2-letter code for your region from the Logz.io Regions and Listener hosts table or from your Account settings page - as in step 3 above.
      logging:

    processors:
      memory_limiter:
        ballast_size_mib: 2000
        check_interval: 1s
        limit_mib: 4000
        spike_limit_mib: 800
      batch:
        send_batch_size: 10000
        timeout: 5s
      probabilistic_sampler:
        hash_seed: 22
        sampling_percentage: 1
      k8s_tagger:
        passthrough: true
      queued_retry:

    extensions:
      pprof:
        endpoint: :1777
      zpages:
        endpoint: :55679
      health_check:

    service:
      extensions: [health_check, pprof]
      pipelines:
        traces:
          processors: [queued_retry, batch, memory_limiter, probabilistic_sampler, k8s_tagger]
          exporters: [logzio]
{{- end -}}