{{- if .Values.secret.enabled -}}
apiVersion: {{ .Values.apiVersions.secret }}
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ .Values.k8sApp }}
    {{- include "logzio-k8s-events.labels" . | nindent 4 }}
type: Opaque
stringData:
  logzio-log-shipping-token: {{ required "Logzio shipping token is required!" (.Values.logzioLogsToken | default .Values.global.logzioLogsToken) }}
  logzio-log-listener: {{ template "logzio-k8s-events.listenerHost" . }}
  env-id: {{ .Values.global.env_id | quote }}
{{- end }}