dependencies:
- name: kube-state-metrics
  version: "2.13.2"
  repository: "https://kubernetes.github.io/kube-state-metrics"
- name: prometheus-node-exporter
  version: "1.16.2"
  repository: "https://github.com/prometheus-community/helm-charts/charts"