# See https://github.com/helm/chart-testing#configuration
all:
debug:
helm-extra-args: --set secrets.MetricsToken=fakeXamgZErKKkMhmzdVZDhuZcpGKXeo --set secrets.p8s_logzio_name=test --set secrets.ListenerHost=https://listener.logz.io:8053