apiVersion: {{ .Values.apiVersions.Secrets }}
kind: Secret
metadata:
  name: logzio-monitoring-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  logzio-traces-shipping-token: {{ .Values.secrets.TracesToken }}
