apiVersion: v2
name: logzio-otel-k8s-metrics
description: logzio-otel-k8s-metrics allows you to ship metrics from your Kubernetes cluster using the OpenTelemetry collector.

type: application

sources:
  - https://github.com/prometheus/node_exporter
  - https://github.com/kubernetes/kube-state-metrics
dependencies:
  - name: kube-state-metrics
    version: "2.13.2"
    repository: https://kubernetes.github.io/kube-state-metrics
    condition: kubeStateMetrics.enabled
  - name: prometheus-node-exporter
    version: "1.18.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: nodeExporter.enabled
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 0.24.0

maintainers:
- name: yotamloe
  email: yotam.loewenbach@logz.io
