{{ if .Values.enabled}}
{{ if .Values.fargateLogRouter.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  filters.conf: |
    [FILTER]
      Name modify
      Match *
      Add token {{ .Values.secrets.logzioLogsToken }}
      Add type {{ .Values.secrets.logType }}
      Rename log message
    [FILTER]
      Name kubernetes
      Match kube.*
      Merge_Log On
      Keep_Log Off
      K8S-Logging.Parser On
      K8S-Logging.Exclude On
    [FILTER]
      Name modify
      Match *
      Condition Key_value_matches message (?i)(error|failure|failed|exception|panic)
      Add log_level ERROR
    [FILTER]
      Name modify
      Match *
      Condition Key_value_matches message (?i)(warn|warning)
      Add log_level WARNING
    [FILTER]
      Name modify
      Match *
      Condition Key_value_does_not_match message (?i)(error|failure|failed|exception|panic|warn|warning)
      Add log_level INFO
  output.conf: |
    [OUTPUT]
      Name  es
      Match *
      Host  {{ template "logzio.listenerAddress" . }}
      HTTP_User token
      HTTP_Passwd {{ .Values.secrets.logzioLogsToken }}
      Port  8070
      Retry_Limit no_retries
      Index logzioCustomerIndex
{{ end }}
{{ end }}