
{{ if .Values.enabled}}
{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  env-id: {{.Values.secrets.env_id | quote}}
  logzio-listener-region: {{ .Values.secrets.logzioRegion}}
  {{ if .Values.secrets.logzioMetricsToken}}
  logzio-metrics-token: {{ .Values.secrets.logzioMetricsToken }}
  {{ end }}
  {{ if .Values.secrets.customEndpoint}}
  custom-endpoint: {{ .Values.secrets.customEndpoint}}
  {{ end }}
  {{ if .Values.secrets.k8sObjectsLogsToken}}
  logzio-k8s-objects-logs-token: {{ .Values.secrets.k8sObjectsLogsToken}}
  {{ end }}
{{- end }}
{{ end }}
