image: logzio/cloudwatch-fetcher
imageTag: 0.0.1

secrets:
  enabled: true
  name: "logzio-logs-secret-cloudwatch"
  logzioShippingToken: ""
  logzioListener: ""
  awsAccessKey: ""
  awsSecretKey: ""

persistentVolume:
  enabled: true
  storageClassName: "logzio-cloudwatch-fetcher"
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Mi

loggingConfig: |
  [loggers]
  keys=root

  [handlers]
  keys=stream_handler

  [formatters]
  keys=formatter

  [logger_root]
  level=INFO
  handlers=stream_handler

  [handler_stream_handler]
  class=StreamHandler
  level=INFO
  formatter=formatter
  args=(sys.stderr,)

  [formatter_formatter]
  format=%(asctime)s %(threadName)-12s %(name)-12s %(levelname)-8s %(message)s

fetcherConfig: ""
resetPositionFile: false
