name: Release flunetd windows docker image

on:
  push:
    branches:
      - ci/dev-work-windows-auto-release-fix
    paths:
      - 'charts/fluentd/docker_windows/fluentd_windows.dockerfile'
      - 'charts/fluentd/docker_windows/fluentd_windows2022.dockerfile'

jobs:
  release-docker-windows:
    name: release fluentd windows 2019 docker image
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get new image version
        id: extract_version
        shell: cmd
        working-directory: charts/fluentd/docker_windows
        run: for /f "tokens=2 delims==" %%a in ('type "fluentd_windows.dockerfile" ^|findstr "version"') do @echo NEW_VERSION=%%a >> %GITHUB_ENV%
      - name: Debug NEW_VERSION
        run: echo "${{ env.NEW_VERSION }}"
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        working-directory: charts/fluentd/docker_windows
        run: |
          docker build -t logzio/fluentd-windows:${{ env.NEW_VERSION }} -t logzio/fluentd-windows:latest --platform windows/amd64 -f fluentd_windows.dockerfile .
          docker push logzio/fluentd-windows:${{ env.NEW_VERSION }} 
          docker push logzio/fluentd-windows:latest

  release-docker-windows2022:
    name: release fluentd windows 2022 docker image
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get new image version
        id: extract_version
        shell: cmd
        working-directory: charts/fluentd/docker_windows
        run: for /f "tokens=2 delims==" %%a in ('type "fluentd_windows2022.dockerfile" ^|findstr "version"') do @echo NEW_VERSION=%%a >> %GITHUB_ENV%
      - name: Debug NEW_VERSION
        run: echo "${{ env.NEW_VERSION }}"
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        working-directory: charts/fluentd/docker_windows
        run: |
          docker build -t logzio/fluentd-windows-2022:${{ env.NEW_VERSION }} -t logzio/fluentd-windows-2022:latest --platform windows/amd64 -f fluentd_windows2022.dockerfile .
          docker push logzio/fluentd-windows-2022:${{ env.NEW_VERSION }} 
          docker push logzio/fluentd-windows-2022:latest