name: Release kube-tools docker image

on:
  push:
    branches:
      - master
    paths:
      - 'charts/logzio-monitoring/plugins/Dockerfile'

jobs:
  release-docker:
    name: release kube-tools docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get new image version
        id: extract_version
        run: echo "NEW_VERSION=$(sed -n 's/^LABEL version="\([0-9.]*\)"/\1/p' charts/logzio-monitoring/plugins/Dockerfile)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64, linux/arm/v7, linux/arm/v8, linux/arm64
          tags: logzio/kube-tools:latest, logzio/kube-tools:${{ env.NEW_VERSION }}
          context: charts/logzio-monitoring/plugins
