name: Release flunetd windows docker image

on:
  push:
    branches:
      - ci/dev-work-windows-auto-release-fix
    paths:
      - 'charts/fluentd/docker_windows/fluentd_windows.dockerfile'
      - 'charts/fluentd/docker_windows/fluentd_windows2022.dockerfile'

jobs:
  release-docker-windows:
    name: release fluentd windows 2019 docker image
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get new image version
        id: extract_version
        shell: cmd
        run: for /f "tokens=2 delims==" %%a in ('type "fluentd_windows.dockerfile" ^|findstr "version"') do @echo NEW_VERSION=%%a >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: windows/amd64
          sbom: true
          provenance: mode=max
          tags: logzio/fluentd-windows:latest, logzio/fluentd-windows:${{ env.NEW_VERSION }}
          context: charts/logzio-fluend/docker_windows
          file: fluentd_windows.dockerfile

  release-docker-windows2022:
    name: release fluentd windows 2022 docker image
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get new image version
        id: extract_version
        shell: cmd
        run: for /f "tokens=2 delims==" %%a in ('type "fluentd_windows.dockerfile" ^|findstr "version"' do @echo NEW_VERSION=%%a) >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: windows/amd64
          sbom: true
          provenance: mode=max
          tags: logzio/fluentd-windows-2022:latest, logzio/fluentd-windows-2022:${{ env.NEW_VERSION }}
          context: charts/logzio-fluend/docker_windows
          file: fluentd_windows2022.dockerfile