name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[skip release]')"
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          
      - id: fetch-latest-release
        uses: gregziegan/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Send message to product integrations
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
        # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "integration_name": "${{ steps.fetch-latest-release.outputs.name }}",
              "new_version": "${{ steps.fetch-latest-release.outputs.tag_name }}" ,
              "changes": ${{ toJSON(github.event.head_commit.message) }},
              "author": "${{ github.event.commits[0].author.name }}",
              "repo_url": "https://github.com/${{github.repository}}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

