name: Helm Template Filter Test

on:
  pull_request:
    branches:
      - master
    paths:
      - 'charts/logzio-apm-collector/Chart.yaml'
      - 'charts/logzio-apm-collector/templates/**'
      - 'charts/logzio-apm-collector/values.yaml'
      - 'charts/logzio-logs-collector/Chart.yaml'
      - 'charts/logzio-logs-collector/templates/**'
      - 'charts/logzio-logs-collector/values.yaml'
      - 'tests/filters/**'
      - 'tests/template_filters_test.go'
      - '.github/workflows/helm-template-filter-test.yaml'

jobs:
  test-helm-template-filters:
    name: Test Helm Template Filters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Run Helm Template Filter Go Test
        run: |
          go test -v ./tests/template_filters_test.go 