name: Test `logzio-k8s-events` chart
on:
  pull_request:
    branches:
      - master
    paths:
      - 'charts/logzio-k8s-events/Chart.yaml'
      - 'charts/logzio-k8s-events/templates/**'
      - 'charts/logzio-k8s-events/values.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Kind
        run: |
          curl -Lo ./kind "https://kind.sigs.k8s.io/dl/v0.11.1/kind-Linux-amd64"
          chmod +x ./kind
          mv ./kind /usr/local/bin/kind

      - name: Create Kind cluster
        run: |
          kind create cluster --name kind-${{ github.run_id }}
          kubectl cluster-info

      - name: Deploy K8S Events Helm Chart
        run: |
          cd charts/logzio-k8s-events
          helm upgrade --install \
          --set global.env_id=${{ env.ENV_ID }} \
          --set global.tolerations[0].key="global-key" \
          --set global.tolerations[0].operator="Equal" \
          --set global.tolerations[0].value="global-value" \
          --set global.tolerations[0].effect="NoSchedule" \
          --set global.logzioLogsToken=${{ secrets.LOGZIO_LOGS_TOKEN }} \
          --set global.logzioRegion=us \
          logzio-k8s-events .

      - name: Verify deployment Status
        run: |
          kubectl rollout status deployment/logzio-k8s-events --timeout=300s
          kubectl get deployment logzio-k8s-events -o json | jq '.status.numberReady == .status.desiredNumberScheduled'
          kubectl get deployment logzio-k8s-events -o jsonpath='{.spec.template.spec.tolerations}' | grep -q 'global-key'

      - name: Cleanup Environment
        run: |
          kind delete cluster --name kind-${{ github.run_id }}