apiVersion: {{ .Values.apiVersions.daemonset }}
kind: DaemonSet
metadata:
  name: filebeat
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: filebeat
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: {{ template "filebeat.serviceAccount" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod }}
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      containers:
      - name: filebeat
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: IGNORE_OLDER
          value: {{ .Values.daemonset.ignoreOlder }}
        - name: LOGZIO_CODEC
          value: {{ .Values.daemonset.logzioCodec }}
        - name: LOGZIO_TYPE
          value: {{ .Values.daemonset.logzioType }}
        - name: FIELDS_UNDER_ROOT
          value: {{ quote .Values.daemonset.fieldsUnderRoot }}
        envFrom:
        - secretRef:
             name: {{ .Values.secrets.name }}
{{- if .Values.extraEnvFrom }}
{{- toYaml .Values.extraEnvFrom | nindent 8 }}
{{- end }}
        securityContext: {{ toYaml ( .Values.daemonset.securityContext ) | nindent 10 }}
        resources: {{ toYaml ( .Values.daemonset.resources ) | nindent 10 }}
        volumeMounts:
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
      {{- range .Values.daemonset.volumeMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          readOnly: {{ .readOnly }}
          subPath: {{ .subPath }}
      {{- end }}
      {{- if .Values.daemonset.tolerations }}
      tolerations:
{{ toYaml .Values.daemonset.tolerations | indent 6 }}
      {{- end }}
      volumes:
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      - name: data
        hostPath:
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
    {{- range .Values.daemonset.volumes }}
      - name: {{ .name }}
        configMap:
          defaultMode: {{ .configMap.defaultMode }}
          name: {{ .configMap.name }}
    {{- end }}
---
apiVersion: {{ .Values.apiVersions.daemonset }}
kind: DaemonSet
metadata:
  name: winlogbeat
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: filebeat
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      serviceAccountName: {{ template "filebeat.serviceAccount" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod }}
      hostNetwork: {{ .Values.windowsHostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      containers:
      - name: winlogbeat
        image: "{{ .Values.winlogbeatImage }}:{{ .Values.winlogbeatImageTag }}"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: IGNORE_OLDER
          value: {{ .Values.winlogbeatDaemonset.ignoreOlder }}
        - name: LOGZIO_CODEC
          value: {{ .Values.winlogbeatDaemonset.logzioCodec }}
        - name: LOGZIO_TYPE
          value: {{ .Values.winlogbeatDaemonset.logzioType }}
        - name: FIELDS_UNDER_ROOT
          value: {{ quote .Values.winlogbeatDaemonset.fieldsUnderRoot }}
        envFrom:
        - secretRef:
             name: {{ .Values.secrets.name }}
{{- if .Values.extraEnvFrom }}
{{- toYaml .Values.extraEnvFrom | nindent 8 }}
{{- end }}
        resources: {{ toYaml ( .Values.winlogbeatDaemonset.resources ) | nindent 10 }}
        volumeMounts:
        - name: data
          mountPath: C:\winlogbeat-7.15.2-windows-x86_64\data
        - name: varlog
          mountPath: C:\var\log
          readOnly: true
      {{- range .Values.winlogbeatDaemonset.volumeMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          readOnly: {{ .readOnly }}
          subPath: {{ .subPath }}
      {{- end }}
      {{- if .Values.winlogbeatDaemonset.tolerations }}
      tolerations:
{{ toYaml .Values.winlogbeatDaemonset.tolerations | indent 6 }}
      {{- end }}
      volumes:
      - name: varlog
        hostPath:
          path: C:\var\log
      - name: data
        hostPath:
          path: C:\var\lib\winlogbeat-data
          type: DirectoryOrCreate
    {{- range .Values.winlogbeatDaemonset.volumes }}
      - name: {{ .name }}
        configMap:
          defaultMode: {{ .configMap.defaultMode }}
          name: {{ .configMap.name }}
    {{- end }}
---
apiVersion: {{ .Values.apiVersions.daemonset }}
kind: DaemonSet
metadata:
  name: filebeat-win
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: filebeat
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      serviceAccountName: {{ template "filebeat.serviceAccount" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod }}
      hostNetwork: {{ .Values.windowsHostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      containers:
      - name: filebeat-win
        image: "{{ .Values.filebeatWindowsImage }}:{{ .Values.filebeatWindowsImageTag }}"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: IGNORE_OLDER
          value: {{ .Values.filebeatWindowsDaemonset.ignoreOlder }}
        - name: LOGZIO_CODEC
          value: {{ .Values.filebeatWindowsDaemonset.logzioCodec }}
        - name: LOGZIO_TYPE
          value: {{ .Values.filebeatWindowsDaemonset.logzioType }}
        - name: FIELDS_UNDER_ROOT
          value: {{ quote .Values.filebeatWindowsDaemonset.fieldsUnderRoot }}
        envFrom:
        - secretRef:
             name: {{ .Values.secrets.name }}
{{- if .Values.extraEnvFrom }}
{{- toYaml .Values.extraEnvFrom | nindent 8 }}
{{- end }}
        resources: {{ toYaml ( .Values.filebeatWindowsDaemonset.resources ) | nindent 10 }}
        volumeMounts:
        - name: data
          mountPath: C:\filebeat-7.15.2-windows-x86_64\data
        - name: varlibdockercontainers
          mountPath: C:\var\lib\docker\containers
          readOnly: true
        - name: varlog
          mountPath: C:\var\log
          readOnly: true
      {{- range .Values.filebeatWindowsDaemonset.volumeMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          readOnly: {{ .readOnly }}
          subPath: {{ .subPath }}
      {{- end }}
      {{- if .Values.filebeatWindowsDaemonset.tolerations }}
      tolerations:
{{ toYaml .Values.filebeatWindowsDaemonset.tolerations | indent 6 }}
      {{- end }}
      volumes:
      - name: varlibdockercontainers
        hostPath:
          path: C:\ProgramData\docker\containers
      - name: varlog
        hostPath:
          path: C:\var\log
      - name: data
        hostPath:
          path: C:\filebeat-7.15.2-windows-x86_64\data
          type: DirectoryOrCreate
    {{- range .Values.filebeatWindowsDaemonset.volumes }}
      - name: {{ .name }}
        configMap:
          defaultMode: {{ .configMap.defaultMode }}
          name: {{ .configMap.name }}
    {{- end }}
#
