{{- if .Values.secrets.create }}
apiVersion: {{ .Values.apiVersions.secret }}
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- if .Values.secrets.logzioShippingToken }}
  LOGZIO_LOGS_SHIPPING_TOKEN: {{ .Values.secrets.logzioShippingToken }}
  {{- end }}
  {{- if .Values.secrets.logzioShippingToken }}
  LOGZIO_LOGS_LISTENER_HOST: {{ template "logzio.listenerHost" . }}
  {{- end }}
  {{- if .Values.secrets.logzioShippingToken }}
  CLUSTER_NAME: {{ .Values.secrets.clusterName }}
  {{- end }}
{{- end -}}