{{- if .Values.secrets.create }}
apiVersion: {{ .Values.apiVersions.secret }}
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  LOGZIO_LOGS_SHIPPING_TOKEN: {{ .Values.secrets.logzioShippingToken }}
  LOGZIO_LOGS_LISTENER_HOST: {{ template "logzio.listenerHost" . }}
  CLUSTER_NAME: {{ .Values.secrets.clusterName }}
{{- end -}}